export interface Theme {
	name: string;
	label: string;
	vars: Record<string, string>;
}

export const DEFAULT_THEME_NAME = 'light';

/** Return a known theme name, falling back to the default when missing or invalid. */
export function resolveThemeName(name: string | null | undefined): string {
	if (name && themes.some((t) => t.name === name)) return name;
	return DEFAULT_THEME_NAME;
}

export const themes: Theme[] = [
	{
		name: 'light',
		label: 'Light',
		vars: {
			'--bg': '#ffffff',
			'--bg-surface': '#f9fafb',
			'--bg-elevated': '#ffffff',
			'--bg-hover': '#f3f4f6',
			'--bg-active': '#eef2ff',
			'--border': '#b0b5be',
			'--border-light': '#d1d5db',
			'--text': '#111827',
			'--text-secondary': '#374151',
			'--text-muted': '#4b5563',
			'--text-faint': '#6b7280',
			'--accent': '#4f46e5',
			'--accent-light': '#c7d2fe',
			'--accent-bg': '#eef2ff',
			'--accent-subject': '#4338ca',
			'--prose-bg': '#ffffff',
			'--prose-text': '#1f2937',
			'--header-bg': '#ffffff',
			'--pane-bg': '#fafbfc',
			'--canvas-bg': '#f0f2f4',
			'--diff-added-color': '#059669',
			'--diff-added-bg': '#ecfdf5',
			'--diff-removed-color': '#dc2626',
			'--feedback-bg': '#fffbeb',
			'--feedback-border': '#f59e0b',
			'--tool-bg': '#f5f3ff',
			'--tool-border': '#ede9fe',
			'--tool-accent': '#7c3aed',
			'--assistant-bg': '#f0fdf4',
			'--assistant-border': '#dcfce7',
			'--color-user-edit': '#d97706',
			'--color-agent-edit': '#059669',
			'--color-pinned': '#7c3aed',
			'--win-bg': '#d1fae5',
			'--win-border': '#10b981',
		}
	},
	{
		name: 'dark',
		label: 'Dark',
		vars: {
			'--bg': '#0f0f0f',
			'--bg-surface': '#1a1a1a',
			'--bg-elevated': '#1e1e1e',
			'--bg-hover': '#2a2a2a',
			'--bg-active': '#1e1b4b',
			'--border': '#444',
			'--border-light': '#333',
			'--text': '#f0f0f0',
			'--text-secondary': '#d4d4d4',
			'--text-muted': '#a8a8a8',
			'--text-faint': '#909090',
			'--accent': '#a5b4fc',
			'--accent-light': '#4338ca',
			'--accent-bg': '#1e1b4b',
			'--accent-subject': '#c7d2fe',
			'--prose-bg': '#0f0f0f',
			'--prose-text': '#e8e8e8',
			'--header-bg': '#2a2a2a',
			'--pane-bg': '#2a2a2a',
			'--canvas-bg': '#0a0a0a',
			'--diff-added-color': '#6ee7b7',
			'--diff-added-bg': '#1a1a1a',
			'--diff-removed-color': '#fca5a5',
			'--feedback-bg': '#422006',
			'--feedback-border': '#d97706',
			'--tool-bg': '#1e1332',
			'--tool-border': '#2e1065',
			'--tool-accent': '#c4b5fd',
			'--assistant-bg': '#1a1a1a',
			'--assistant-border': '#333',
			'--color-user-edit': '#fbbf24',
			'--color-agent-edit': '#6ee7b7',
			'--color-pinned': '#c4b5fd',
			'--win-bg': 'rgba(16, 185, 129, 0.18)',
			'--win-border': '#10b981',
		}
	},
	{
		name: 'solarized-light',
		label: 'Solarized Light',
		vars: {
			'--bg': '#fdf6e3',
			'--bg-surface': '#eee8d5',
			'--bg-elevated': '#fdf6e3',
			'--bg-hover': '#eee8d5',
			'--bg-active': '#d5cdb6',
			'--border': '#c9bea5',
			'--border-light': '#d6ccb2',
			'--text': '#073642',
			'--text-secondary': '#586e75',
			'--text-muted': '#657b83',
			'--text-faint': '#93a1a1',
			'--accent': '#268bd2',
			'--accent-light': '#b3d7f0',
			'--accent-bg': '#e8f3fb',
			'--accent-subject': '#2aa198',
			'--prose-bg': '#fdf6e3',
			'--prose-text': '#073642',
			'--header-bg': '#fdf6e3',
			'--pane-bg': '#fdf6e3',
			'--canvas-bg': '#eee8d5',
			'--diff-added-color': '#859900',
			'--diff-added-bg': '#f0f4e0',
			'--diff-removed-color': '#dc322f',
			'--feedback-bg': '#f5efd8',
			'--feedback-border': '#b58900',
			'--tool-bg': '#eee8d5',
			'--tool-border': '#d6ccb2',
			'--tool-accent': '#6c71c4',
			'--assistant-bg': '#eee8d5',
			'--assistant-border': '#d6ccb2',
			'--color-user-edit': '#b58900',
			'--color-agent-edit': '#859900',
			'--color-pinned': '#6c71c4',
			'--win-bg': '#e9f5e6',
			'--win-border': '#859900',
		}
	},
	{
		name: 'solarized-dark',
		label: 'Solarized Dark',
		vars: {
			'--bg': '#002b36',
			'--bg-surface': '#073642',
			'--bg-elevated': '#073642',
			'--bg-hover': '#0a4050',
			'--bg-active': '#0d4f5e',
			'--border': '#2a5662',
			'--border-light': '#1a4652',
			'--text': '#eee8d5',
			'--text-secondary': '#d5cdb6',
			'--text-muted': '#93a1a1',
			'--text-faint': '#839496',
			'--accent': '#268bd2',
			'--accent-light': '#0d4f6e',
			'--accent-bg': '#073642',
			'--accent-subject': '#2aa198',
			'--prose-bg': '#002b36',
			'--prose-text': '#eee8d5',
			'--header-bg': '#227f97',
			'--pane-bg': '#227f97',
			'--canvas-bg': '#002b36',
			'--diff-added-color': '#859900',
			'--diff-added-bg': '#1a3a00',
			'--diff-removed-color': '#dc322f',
			'--feedback-bg': '#3a2a00',
			'--feedback-border': '#b58900',
			'--tool-bg': '#1a2040',
			'--tool-border': '#2a3060',
			'--tool-accent': '#6c71c4',
			'--assistant-bg': '#073642',
			'--assistant-border': '#2a5662',
			'--color-user-edit': '#b58900',
			'--color-agent-edit': '#859900',
			'--color-pinned': '#6c71c4',
			'--win-bg': 'color-mix(in srgb, #859900 16%, transparent)',
			'--win-border': '#859900',
		}
	},
	{
		name: 'monokai',
		label: 'Monokai',
		vars: {
			'--bg': '#272822',
			'--bg-surface': '#2e2f2a',
			'--bg-elevated': '#3e3d32',
			'--bg-hover': '#3e3d32',
			'--bg-active': '#49483e',
			'--border': '#49483e',
			'--border-light': '#3e3d32',
			'--text': '#f8f8f2',
			'--text-secondary': '#cfcfc2',
			'--text-muted': '#a6a698',
			'--text-faint': '#908970',
			'--accent': '#a6e22e',
			'--accent-light': '#4a6310',
			'--accent-bg': '#3a4a10',
			'--accent-subject': '#66d9ef',
			'--prose-bg': '#272822',
			'--prose-text': '#f8f8f2',
			'--header-bg': '#484740',
			'--pane-bg': '#484740',
			'--canvas-bg': '#1d1e19',
			'--diff-added-color': '#a6e22e',
			'--diff-added-bg': '#3a4a10',
			'--diff-removed-color': '#f92672',
			'--feedback-bg': '#4a3a10',
			'--feedback-border': '#e6db74',
			'--tool-bg': '#3e3d32',
			'--tool-border': '#49483e',
			'--tool-accent': '#ae81ff',
			'--assistant-bg': '#2e2f2a',
			'--assistant-border': '#49483e',
			'--color-user-edit': '#e6db74',
			'--color-agent-edit': '#a6e22e',
			'--color-pinned': '#ae81ff',
			'--win-bg': 'color-mix(in srgb, #a6e22e 22%, transparent)',
			'--win-border': '#a6e22e',
		}
	}
];

export function applyTheme(theme: Theme) {
	const root = document.documentElement;
	for (const [key, value] of Object.entries(theme.vars)) {
		root.style.setProperty(key, value);
	}
}
